import fs from "fs";
import path from "path";
import CertificatesClient from "../../components/certificates/CertificatesClient";
import { SectionHeading } from "../../components/ui/SectionHeading";
import { autoGenerateDataJson } from "../../utils/certificateParser";

export default async function CertificatesPage() {
  const publicCertificatesDir = path.join(process.cwd(), "public", "certificates");
  
  let events: { id: string; name: string }[] = [];

  try {
    if (fs.existsSync(publicCertificatesDir)) {
      const directories = fs.readdirSync(publicCertificatesDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

      for (const dir of directories) {
        const folderPath = path.join(publicCertificatesDir, dir);
        // Ensure data.json exists by running the parser
        autoGenerateDataJson(folderPath, dir);

        const dataPath = path.join(folderPath, "data.json");
        if (fs.existsSync(dataPath)) {
          const fileContents = fs.readFileSync(dataPath, "utf8");
          const data = JSON.parse(fileContents);
          events.push({
            id: dir,
            name: data.eventName || dir,
          });
        } else {
          // Fallback if data.json is missing but folder exists
          events.push({
            id: dir,
            name: dir,
          });
        }
      }
    } else {
      // Default fallback if dir doesn't exist
      events = [{ id: "default-event", name: "Default Event" }];
    }
  } catch (error) {
    console.error("Error reading certificate directories:", error);
    events = [{ id: "error", name: "Error loading events" }];
  }

  return (
    <div className="min-h-screen bg-void pt-20 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <SectionHeading as="h1" className="mb-4">
            Certificate Portal
          </SectionHeading>
          <p className="font-ui text-steel max-w-2xl mx-auto text-lg">
            Access and download your verified HWI JDCOEM certificates.
          </p>
        </div>
        <CertificatesClient initialEvents={events} />
      </div>
    </div>
  );
}
