import fs from "fs";
import path from "path";
import CertificatesClient from "../components/CertificatesClient";
import { autoGenerateDataJson } from "../utils/import-excel";

export const dynamic = "force-dynamic";

export default function Page() {
  const eventsDir = path.join(process.cwd(), "public/certificates");
  
  if (!fs.existsSync(eventsDir)) {
    fs.mkdirSync(eventsDir, { recursive: true });
  }

  const dirs = fs.readdirSync(eventsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  const events = [];

  for (const dirName of dirs) {
    const dirPath = path.join(eventsDir, dirName);
    const dataJsonPath = path.join(dirPath, "data.json");
    
    if (!fs.existsSync(dataJsonPath)) {
      autoGenerateDataJson(dirPath, dirName);
    }
    
    let eventName = dirName;
    if (fs.existsSync(dataJsonPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(dataJsonPath, "utf-8"));
        if (data.eventName) {
          eventName = data.eventName;
        }
      } catch (e) {
      }
    }
    
    events.push({ id: dirName, name: eventName });
  }

  if (events.length === 0) {
    events.push({ id: "demo-event", name: "Demo Event (Please upload data)" });
  }

  return (
    <>
      <div className="bg-aurora"></div>
      <div className="bg-grid"></div>
      
      <div className="container">
        <header className="header">
          <div className="logo">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L2 7L12 12L22 7L12 2Z" stroke="url(#paint0_linear)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M2 17L12 22L22 17" stroke="url(#paint0_linear)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M2 12L12 17L22 12" stroke="url(#paint0_linear)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <defs>
                <linearGradient id="paint0_linear" x1="2" y1="2" x2="22" y2="22" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#A855F7"/>
                  <stop offset="1" stopColor="#06B6D4"/>
                </linearGradient>
              </defs>
            </svg>
            <span>CertiPro</span>
          </div>
          <nav className="nav-links">
            <a href="#">Home</a>
            <a href="#">Verify</a>
            <a href="#">Features</a>
          </nav>
          <a href="#" className="nav-login">Admin Login</a>
        </header>

        <section className="hero">
          <h1>Verify & Generate<br/>Official Certificates</h1>
          <p>Securely search, verify, and instantly download authentic digital certificates issued by authorized organizations.</p>
        </section>

        <div className="portal-wrapper">
          <div className="glass-panel app-container">
            <CertificatesClient events={events} />
          </div>
        </div>

        <section className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
            </div>
            <h3>Bank-Grade Security</h3>
            <p>End-to-End Encryption & GDPR Compliance. Your data is protected by industry-standard security protocols ensuring complete privacy.</p>
          </div>
          
          <div className="feature-card">
            <div className="feature-icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
            </div>
            <h3>Instant PDF Export</h3>
            <p>Instantly access high-resolution digital certificates with secure PDF downloads available 24/7 across all of your devices.</p>
          </div>
          
          <div className="feature-card">
            <div className="feature-icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><path d="M9 12l2 2 4-4"></path></svg>
            </div>
            <h3>Guaranteed Authentic</h3>
            <p>Official verification against our secure database. Every certificate is verifiable to prevent fraud and ensure absolute integrity.</p>
          </div>
        </section>
      </div>
    </>
  );
}
