import fs from "fs";
import path from "path";
import * as XLSX from "xlsx";

export function autoGenerateDataJson(
  folderPath: string,
  folderName: string
): boolean {
  try {
    const files = fs.readdirSync(folderPath);

    const xlsxFile = files.find(
      (file) =>
        file.toLowerCase().endsWith(".xlsx") &&
        !file.startsWith("~$")
    );

    if (!xlsxFile) {
      console.log(`No Excel file found for ${folderName}`);
      return false;
    }

    const xlsxPath = path.join(folderPath, xlsxFile);

    const workbook = XLSX.readFile(xlsxPath);

    if (!workbook.SheetNames.length) {
      console.error(`No sheets found in ${xlsxFile}`);
      return false;
    }

    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];

    const rows = XLSX.utils.sheet_to_json<any[]>(worksheet, {
      header: 1,
      defval: ""
    });

    if (rows.length < 2) {
      console.error(`Excel file is empty: ${xlsxFile}`);
      return false;
    }

    let headerRowIndex = -1;
    let usnColIndex = -1;
    let nameColIndex = -1;
    let certificateColIndex = -1;

    // Find headers
    for (let r = 0; r < rows.length; r++) {
      const row = rows[r];

      if (!Array.isArray(row)) continue;

      const headers = row.map((cell) =>
        String(cell || "").trim().toLowerCase()
      );

      const uIdx = headers.findIndex(
        (header) =>
          header === "usn" ||
          header.includes("usn") ||
          header === "id" ||
          header.includes("student id")
      );

      const nIdx = headers.findIndex(
        (header) =>
          (header === "name" ||
            header.includes("student name") ||
            header.includes("participant name") ||
            header.includes("participant")) &&
          !header.includes("college") &&
          !header.includes("team")
      );

      const cIdx = headers.findIndex(
        (header) =>
          header.includes("certificate") ||
          header.includes("type") ||
          header.includes("category") ||
          header.includes("applying as")
      );

      if (uIdx !== -1 && nIdx !== -1) {
        headerRowIndex = r;
        usnColIndex = uIdx;
        nameColIndex = nIdx;
        certificateColIndex = cIdx;
        break;
      }
    }

    if (headerRowIndex === -1) {
      console.error(
        `Could not find USN and Name columns in ${xlsxFile}`
      );
      return false;
    }

    const participants: {
      name: string;
      usn: string;
      certificate: string;
    }[] = [];

    // Read student rows
    for (let r = headerRowIndex + 1; r < rows.length; r++) {
      const row = rows[r];

      if (!Array.isArray(row)) continue;

      const usnValue = row[usnColIndex];
      const nameValue = row[nameColIndex];

      if (!usnValue || !nameValue) continue;

      const usn = String(usnValue).trim().toUpperCase();
      const name = String(nameValue).trim();

      let certificate = "participation";

      if (
        certificateColIndex !== -1 &&
        row[certificateColIndex]
      ) {
        const value = String(row[certificateColIndex])
          .trim()
          .toLowerCase();

        if (
          value === "winner" ||
          value === "lead" ||
          value === "president"
        ) {
          certificate = "winner";
        } else {
          certificate = "participation";
        }
      }

      participants.push({
        name,
        usn,
        certificate
      });
    }

    // Remove duplicate USNs
    const uniqueParticipants = Array.from(
      new Map(
        participants.map((student) => [
          student.usn,
          student
        ])
      ).values()
    );

    const outputData = {
      eventName: formatEventName(folderName),
      participants: uniqueParticipants
    };

    const dataJsonPath = path.join(
      folderPath,
      "data.json"
    );

    // IMPORTANT:
    // Always update data.json from Excel.
    fs.writeFileSync(
      dataJsonPath,
      JSON.stringify(outputData, null, 2),
      "utf8"
    );

    console.log(
      `Certificate data generated for ${folderName}: ${uniqueParticipants.length} students`
    );

    return true;
  } catch (error) {
    console.error(
      `Error processing ${folderName}:`,
      error
    );

    return false;
  }
}

function formatEventName(folderName: string) {
  return folderName
    .replace(/-/g, " ")
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}