import fs from "fs";
import path from "path";
import * as XLSX from "xlsx";

export function autoGenerateDataJson(folderPath: string, folderName: string) {
  try {
    const dataJsonPath = path.join(folderPath, "data.json");
    if (fs.existsSync(dataJsonPath)) {
      return; // Already exists
    }

    // Find any .xlsx or .csv file ignoring ~$ temp files
    const files = fs.readdirSync(folderPath);
    const dataFile = files.find((f) => (f.endsWith(".xlsx") || f.endsWith(".csv")) && !f.startsWith("~$"));
    if (!dataFile) {
      return; // No excel/csv file to process
    }

    const dataPath = path.join(folderPath, dataFile);
    const workbook = XLSX.readFile(dataPath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];

    // Read as 2D array
    const rawData = XLSX.utils.sheet_to_json<any[]>(worksheet, { header: 1 });

    if (rawData.length < 2) return;

    let headerRowIdx = -1;
    let usnColIdx = -1;
    let nameColIdx = -1;
    let typeColIdx = -1;

    // Find header row
    for (let i = 0; i < rawData.length; i++) {
      const row = rawData[i];
      if (!Array.isArray(row)) continue;

      for (let j = 0; j < row.length; j++) {
        const cell = String(row[j] || "").trim().toLowerCase();
        if (cell.includes("usn")) {
          usnColIdx = j;
        } else if (
          (cell.includes("student") || cell.includes("participant") || cell === "name" || cell.includes("name")) &&
          !cell.includes("team") &&
          !cell.includes("college")
        ) {
          nameColIdx = j;
        } else if (cell.includes("certificate") || cell.includes("type") || cell.includes("category")) {
          typeColIdx = j;
        }
      }

      if (nameColIdx !== -1) { // Only name is strictly required now
        headerRowIdx = i;
        break;
      }
    }

    if (headerRowIdx === -1) {
      console.error(`Could not identify Name header in ${dataFile}`);
      return;
    }

    const participants = [];
    let autoUsnCounter = 1;

    for (let i = headerRowIdx + 1; i < rawData.length; i++) {
      const row = rawData[i];
      if (!Array.isArray(row)) continue;

      const nameRaw = row[nameColIdx];
      const typeRaw = typeColIdx !== -1 ? row[typeColIdx] : null;

      if (!nameRaw) continue; // Skip empty rows

      const name = String(nameRaw).trim();
      let usn = "";
      
      if (usnColIdx !== -1 && row[usnColIdx]) {
        usn = String(row[usnColIdx]).trim().toUpperCase();
      } else {
        // Auto-generate USN if not provided
        usn = `HWI${autoUsnCounter.toString().padStart(3, '0')}`;
        autoUsnCounter++;
      }

      const certificate = typeRaw ? String(typeRaw).trim().toLowerCase() : "participation";

      if (usn && name) {
        participants.push({ name, usn, certificate });
      }
    }

    const outputData = {
      eventName: formatEventName(folderName),
      participants,
    };

    fs.writeFileSync(dataJsonPath, JSON.stringify(outputData, null, 2));
    console.log(`Successfully generated data.json for ${folderName}`);
  } catch (error) {
    console.error(`Error processing folder ${folderName}:`, error);
  }
}

function formatEventName(dirName: string) {
  return dirName
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
