import fs from "fs";
import path from "path";
import * as XLSX from "xlsx";

export function autoGenerateDataJson(
  folderPath: string,
  folderName: string
): boolean {
  try {
    const dataJsonPath = path.join(folderPath, "data.json");
    // Removed early exit so data.json ALWAYS updates from Excel (per teammate commit)

    // Find any .xlsx or .csv file ignoring ~$ temp files (from main)
    const files = fs.readdirSync(folderPath);
    const dataFile = files.find((f) => (f.endsWith(".xlsx") || f.endsWith(".csv")) && !f.startsWith("~$"));
    if (!dataFile) {
      console.log(`No Excel or CSV file found for ${folderName}`);
      return false;
    }

    const dataPath = path.join(folderPath, dataFile);
    const workbook = XLSX.readFile(dataPath);

    if (!workbook.SheetNames.length) {
      console.error(`No sheets found in ${dataFile}`);
      return false;
    }

    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];

    const rows = XLSX.utils.sheet_to_json<any[]>(worksheet, {
      header: 1,
      defval: ""
    });

    if (rows.length < 2) {
      console.error(`File is empty: ${dataFile}`);
      return false;
    }

    let headerRowIndex = -1;
    let usnColIndex = -1;
    let nameColIndex = -1;
    let certificateColIndex = -1;

    // Find headers
    for (let r = 0; r < rows.length; r++) {
      const row = rows[r];

      if (!Array.isArray(row)) continue;

      const headers = row.map((cell) =>
        String(cell || "").trim().toLowerCase()
      );

      // Advanced column matching from teammate commit
      const uIdx = headers.findIndex(
        (header) =>
          header === "usn" ||
          header.includes("usn") ||
          header === "id" ||
          header.includes("student id")
      );

      const nIdx = headers.findIndex(
        (header) =>
          (header === "name" ||
            header.includes("student name") ||
            header.includes("participant name") ||
            header.includes("participant")) &&
          !header.includes("college") &&
          !header.includes("team")
      );

      const cIdx = headers.findIndex(
        (header) =>
          header.includes("certificate") ||
          header.includes("type") ||
          header.includes("category") ||
          header.includes("applying as")
      );

      // Only name is strictly required now (from main)
      if (nIdx !== -1) {
        headerRowIndex = r;
        usnColIndex = uIdx;
        nameColIndex = nIdx;
        certificateColIndex = cIdx;
        break;
      }
    }

    if (headerRowIndex === -1) {
      console.error(`Could not identify Name header in ${dataFile}`);
      return false;
    }

    const participants: {
      name: string;
      usn: string;
      certificate: string;
    }[] = [];

    let autoUsnCounter = 1;

    // Read student rows
    for (let r = headerRowIndex + 1; r < rows.length; r++) {
      const row = rows[r];

      if (!Array.isArray(row)) continue;

      const nameRaw = row[nameColIndex];
      const typeRaw = certificateColIndex !== -1 ? row[certificateColIndex] : null;

      if (!nameRaw) continue; // Skip empty rows

      const name = String(nameRaw).trim();
      let usn = "";
      
      if (usnColIndex !== -1 && row[usnColIndex]) {
        usn = String(row[usnColIndex]).trim().toUpperCase();
      } else {
        // Auto-generate USN if not provided (from main)
        usn = `HWI${autoUsnCounter.toString().padStart(3, '0')}`;
        autoUsnCounter++;
      }

      let certificate = "participation";

      if (typeRaw) {
        const value = String(typeRaw).trim().toLowerCase();
        if (value === "winner" || value === "lead" || value === "president") {
          certificate = "winner";
        }
      }

      participants.push({
        name,
        usn,
        certificate
      });
    }

    // Remove duplicate USNs (from teammate)
    const uniqueParticipants = Array.from(
      new Map(
        participants.map((student) => [
          student.usn,
          student
        ])
      ).values()
    );

    const outputData = {
      eventName: formatEventName(folderName),
      participants: uniqueParticipants
    };

    // IMPORTANT: Always update data.json from Excel.
    fs.writeFileSync(
      dataJsonPath,
      JSON.stringify(outputData, null, 2),
      "utf8"
    );

    console.log(
      `Certificate data generated for ${folderName}: ${uniqueParticipants.length} students`
    );

    return true;
  } catch (error) {
    console.error(`Error processing ${folderName}:`, error);
    return false;
  }
}

function formatEventName(folderName: string) {
  return folderName
    .replace(/-/g, " ")
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}