import fs from "fs";
import path from "path";
import * as XLSX from "xlsx";

export function autoGenerateDataJson(folderPath: string, folderName: string): boolean {
  try {
    const files = fs.readdirSync(folderPath);
    const xlsxFile = files.find(f => f.endsWith(".xlsx") && !f.startsWith("~$"));
    
    if (!xlsxFile) return false;

    const workbook = XLSX.readFile(path.join(folderPath, xlsxFile));
    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];
    
    // Convert to array of arrays
    const rows = XLSX.utils.sheet_to_json<any[]>(sheet, { header: 1 });

    if (rows.length < 2) return false;

    let headerRowIndex = -1;
    let usnColIndex = -1;
    let nameColIndex = -1;
    let certColIndex = -1;

    for (let r = 0; r < rows.length; r++) {
      const row = rows[r];
      if (!Array.isArray(row)) continue;
      
      const sanitized = row.map(c => c ? String(c).trim().toLowerCase() : "");
      const uIdx = sanitized.findIndex(c => c.includes("usn") || c.includes("email") || c.includes("mobile"));
      const nIdx = sanitized.findIndex(c => 
        c.includes("name") && !c.includes("college") && !c.includes("team") && !c.includes("event")
      );

      if (uIdx !== -1 && nIdx !== -1) {
        headerRowIndex = r;
        usnColIndex = uIdx;
        nameColIndex = nIdx;
        certColIndex = sanitized.findIndex(c => c.includes("certificate") || c.includes("type") || c.includes("winner") || c.includes("applying as"));
        break;
      }
    }

    if (headerRowIndex === -1) return false;

    const participants = [];
    
    for (let r = headerRowIndex + 1; r < rows.length; r++) {
      const row = rows[r];
      if (!row || !row.length) continue;
      
      const nameVal = row[nameColIndex];
      const usnVal = row[usnColIndex];
      
      if (!nameVal || !usnVal) continue;

      const name = String(nameVal).trim();
      const usn = String(usnVal).trim().toUpperCase();
      let certType = "participation";
      
      if (certColIndex !== -1 && row[certColIndex]) {
        let val = String(row[certColIndex]).trim().toLowerCase();
        if (val === "lead" || val === "president") {
          certType = "winner";
        } else if (val === "member") {
          certType = "participation";
        } else {
          certType = val;
        }
      }

      participants.push({
        name,
        usn,
        certificate: certType
      });
    }

    const outputData = {
      eventName: formatFolderName(folderName),
      participants
    };

    fs.writeFileSync(path.join(folderPath, "data.json"), JSON.stringify(outputData, null, 2));
    return true;
  } catch (error) {
    console.error(`Error auto-generating data.json for ${folderName}:`, error);
    return false;
  }
}

function formatFolderName(name: string) {
  return name.replace(/-/g, " ").replace(/\b\w/g, l => l.toUpperCase());
}
